### ISSUE TITLE
Setting fields description text.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [makewebbetter-com/get-a-quote#39]
WordPress version: 5.6.2
Area Path: Admin panel --> MakeWebBetter --> get-a-quote
Status: new
Version: 1.0.0
Description: If required we can add description text for admin with setting fields.

**Comment by Shailesh-cedcoss** [comment]
Done

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
