### ISSUE TITLE
Zipcode and Phone Number field showing console error.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [makewebbetter-com/get-a-quote#46]
WordPress version: 5.7.1
Area Path: Site --> Quote Form
Status: new
Version: 1.0.1
Description: The Zipcode and Phone Number field showing console errors.
Initial console error: GET http://localhost:10024/wp-content/plugins/get-a-quote/public/src/scss/bootstrap.min.css?ver=1.0.0 net::ERR_ABORTED 404 (Not Found)

After filling Zipcode and Phone Number field:
![screen4](https://user-images.githubusercontent.com/76723329/115658155-d66dcd80-a355-11eb-9636-4a7e29e7b4b2.jpg)

After Submitting form:
![screen5](https://user-images.githubusercontent.com/76723329/115690785-04193d80-a37b-11eb-8911-356854f2bf5e.jpg)

**Comment by Shailesh-cedcoss** [comment]
Done

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
