### ISSUE TITLE
Quote Form is getting submitted if it is disabled from admin panel before submitting.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [makewebbetter-com/get-a-quote#47]
WordPress version: 5.7.1
Area Path: Site --> Quote Form
Status: new
Version: 1.0.1
Description: The Quote Form is getting submitted if it is disabled from the admin panel before submitting.
![Screenshot (46)](https://user-images.githubusercontent.com/76723329/115659814-be4b7d80-a358-11eb-91d7-f4cbf58b5cf3.png)
![Screenshot (47)](https://user-images.githubusercontent.com/76723329/115660075-1f735100-a359-11eb-9c21-df907e7beed6.png)

**Comment by Shailesh-cedcoss** [comment]
Done

**Comment by ChiragGupta-CEDCOSS** [comment]
Working fine.
