### ISSUE TITLE
Preloader can be added on Quote Form.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [makewebbetter-com/get-a-quote#48]
WordPress version: 5.7.1
Area Path: Site --> Quote Form
Status: new
Version: 1.0.1
Description: The Preloader can be added on Quote Form, when the user submits form user will get to know that form submission is in the process as submission takes some time.

**Comment by Shailesh-cedcoss** [comment]
Mention this in the idea section we will later think on this for update

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
