### ISSUE TITLE
QA issues

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [makewebbetter-com/get-a-quote#49]
Plugin name: Get A Quote
Version: 1.0.1

**QA issues:** 
Commented code:
/home/cedcoss/Local Sites/mwb-testing/app/public/wp-content/plugins/get-a-quote/admin/src/scss/get-a-quote-admin.css line: 920

Update Comment Information:
/home/cedcoss/Local Sites/mwb-testing/app/public/wp-content/plugins/get-a-quote/get-a-quote.php line: 18-25

click - onclick:
/home/cedcoss/Local Sites/mwb-testing/app/public/wp-content/plugins/get-a-quote/admin/src/js/get-a-quote-admin.js line: 706, 805

**Comment by Shailesh-cedcoss** [comment]
Done

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
