### ISSUE TITLE
Content needs to be updated if the Quote form is disabled from settings

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [makewebbetter-com/get-a-quote#51]
WordPress version: 5.8.1
Area Path: Site --> Quote Form
Version: 1.0.1
Description: Content needs to be updated if the Quote form is disabled from settings.
![Screenshot - 2021-11-01T125508 393](https://user-images.githubusercontent.com/76723329/139655107-a604037b-a1f6-4333-931a-538e900da30b.png)

**Comment by ChiragGupta-CEDCOSS** [comment]
Still left.

**Comment by Shailesh-cedcoss** [comment]
Fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
