### ISSUE TITLE
Sidebar is not coming fine with form.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [makewebbetter-com/get-a-quote#52]
WordPress version: 5.8.1
Area Path: Site --> Quote Form
Version: 1.0.1
Description: Sidebar is not coming fine with form.
![Screenshot - 2021-11-01T130637 779](https://user-images.githubusercontent.com/76723329/139655505-55f8246a-8686-43e3-a952-c12071b60cb3.png)

**Comment by ChiragGupta-CEDCOSS** [comment]
Still left.

**Comment by Shailesh-cedcoss** [comment]
Fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
