### ISSUE TITLE
Error messages for fields validation are showing on Quote Form.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [makewebbetter-com/get-a-quote#53]
WordPress version: 5.8.1
Area Path: Site --> Quote Form
Version: 1.0.1
Description: Error messages for fields validation are not showing on Quote Form.
![Screenshot - 2021-11-01T162314 830](https://user-images.githubusercontent.com/76723329/139662170-162d88ae-4c92-48bc-aee9-eb336146eaaa.png)
![Screenshot - 2021-11-01T162341 282](https://user-images.githubusercontent.com/76723329/139662190-939c5899-6f3a-486b-9f8f-fcf6103fc378.png)

**Comment by Shailesh-cedcoss** [comment]
Fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Still left Validation error messages are not coming.

**Comment by Shailesh-cedcoss** [comment]
Fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
